### ISSUE TITLE
Build stuck due to Web3Provider

### ISSUE THREAD

**Issue by aashutoshrathi** [stackrlabs/docs#16]
## Description

Right now the `vite build` never exits which is reproducible locally as well as on the deployment service (Vercel in this case), which causes the issues in build. The root cause of issue is one of `WagmiProvider` or `RainbowKitProvider`. When we remove them and their uses through out the application the build works.

### What needs to be done?

Since we need wallet connection to be able to invoke Metamask's signing for Registration & NFT Claim, **we need a better web3 provide**r which builds with vite, the issue is most likely related to something that can't be built on Server side or waits indefinitely to get a value from some external service.

**Comment by Dhruv-2003** [comment]
I have tried using Web3Modal from Walletconnect along with Wagmi , and the build fails now. It's because of the fact that Web3Modal uses @radix-ui internally.

**Comment by Dhruv-2003** [comment]
```
✖ bundles failed to build: node_modules/@radix-ui/react-dialog/node_modules/react-remove-scroll/dist/es2015/SideEffect.js (1:9): "__spreadArray" is not exported by "node_modules/tslib/tslib.es6.js", imported by "node_modules/@radix-ui/react-dialog/node_modules/react-remove-scroll/dist/es2015/SideEffect.js".
file: /Users/dhruv/Developer/Stackr/Core/docs/node_modules/@radix-ui/react-dialog/node_modules/react-remove-scroll/dist/es2015/SideEffect.js:1:9
1: import { __spreadArray } from "tslib";
            ^
2: import * as React from 'react';
3: import { RemoveScrollBar } from 'react-remove-scroll-bar';
error: script "build" exited with code 1
```

**Comment by aashutoshrathi** [comment]
@Dhruv-2003 can you link the draft PR/branch on which you are getting this?

**Comment by aashutoshrathi** [comment]
@Dhruv-2003 not getting any such error on my end in your branch, the build is not throwing error, it's just stuck after `[built] in 19.733s` as earlier.
Is there more code in your branch that you haven't pushed?

**Comment by Dhruv-2003** [comment]
> @Dhruv-2003 not getting any such error on my end in your branch, the build is not throwing error, it's just stuck after `[built] in 19.733s` as earlier. Is there more code in your branch that you haven't pushed?

Ohh yeah , I don't know for some reason 2 of the files I changed got reverted. Let me redo it

**Comment by Dhruv-2003** [comment]
@aashutoshrathi , I just pushed the code , this doesn't have the old provider , I stripped it all and even removed rainbowkit. It throws the error I was mentioning.
