### ISSUE TITLE
Update Docs as per v0.5.0 changes

### ISSUE THREAD

**Issue by aashutoshrathi** [stackrlabs/docs#23]

**Comment by Dhruv-2003** [comment]
To update / Add :

- [x] Batches
- [x] Hooks ( What & How )
- [x] Events update
- [x] Empty Blocks

Others: 

- [x] waitFor
- [x] Logs & error

**Comment by eshaan7** [comment]
For changelog, refer to the [PR](https://github.com/stackrlabs/sdk/pull/269) description.
